### ISSUE TITLE
Move to thread

### ISSUE THREAD

**Issue by amritsinghcse** [SuperHaker/Say-Hi#1]
TTS working in main thread. Move it to background.

**Comment by replyashu** [comment]
TTS is text to speech which I could interpret, right?

**Comment by kevinah95** [comment]
I'm working on it, now!

**Comment by replyashu** [comment]
I am finishing it off in next 20 mins or so :)

**Comment by replyashu** [comment]
Done, Kindly verify !

**Comment by amritsinghcse** [comment]
Right.

**Comment by amritsinghcse** [comment]
@replyashu Nice. Open a pull request so I can merge it

**Comment by replyashu** [comment]
@SuperHaker done
