### ISSUE TITLE
UI improvement (Material Design)

### ISSUE THREAD

**Issue by amritsinghcse** [SuperHaker/Say-Hi#2]
Improvement in UI for both below and above API 21.

**Comment by rrishabhj** [comment]
hey i want to help. What do you thinking for improvement?

**Comment by amritsinghcse** [comment]
@rrishabhj Use of colors more appropriate to favicon. Animated Spinner and Button like ripple effect etc.

**Comment by shivamarora96** [comment]
i would like to contribute to this project. @SuperHaker

**Comment by rrishabhj** [comment]
@SuperHaker ok i am working on it!
